### PR TITLE
Button Style Fixes

### LINKED ISSUE #239: Button Dimension Inconsistencies
If a button only has an icon, its height is shorter by 6px than a button with text.
screen shot 2016-03-29 at 6 35 05 pm
The dimension of buttons is set by padding and margins and thus why the height is different. I was able to work around this when creating the loading button but it's causing problems when we mix icon-only buttons and buttons with text in buttonGroups.
screen shot 2016-03-29 at 6 08 42 pm

If I try to work around this by setting the `minHeight: 15` on the button, the icon is offset. I can't override the negative margins used on the icon because it's set on the `Icon` itself.
screen shot 2016-03-29 at 6 32 24 pm

A better way to handle this at the button level rather than trying to make up for it in the respective pieces.

### PR DESCRIPTION
**Pull request by iheartrachie**
This updates the button styles to match the [style guide](https://app.frontify.com/d/KHQZnlj1XMIO/web-patterns#/components/buttons/button-types). It should also close #239. This is CSS only, no other changes.

## Before
wqhcorylos

## After
bdipsgzbse

### CODE REVIEW

File: src/components/Button.js [hunk 1]
```diff
@@ -135,30 +136,47 @@ const Button = React.createClass({
         ':hover': {
           color: StyleConstants.adjustColor(this.props.primaryColor, -8),
           fill: StyleConstants.adjustColor(this.props.primaryColor, -8),
-          transition: 'all .2s ease-in'
+          transition: 'all .2s ease-in',
+          borderColor: StyleConstants.Colors.FOG,
+          borderRadius: 2,
+          borderWidth: 1
```
Comment (scotttball) [inline src/components/Button.js]: `borderWidth` can be combined with `borderColor` = `border: '1px solid' + StyleConstants.Colors.FOG`

File: src/components/Button.js [hunk 2]
```diff
@@ -135,30 +136,47 @@ const Button = React.createClass({
...
-          transition: 'all .2s ease-in'
+          transition: 'all .2s ease-in',
+          backgroundColor: StyleConstants.Colors.PORCELAIN
+        }
+      },
+      neutral: {
+        backgroundColor: 'transparent',
+        borderColor: StyleConstants.Colors.FOG,
+        borderRadius: 2,
+        borderWidth: 1,
```
Comment (scotttball) [inline src/components/Button.js]: same

File: src/components/Button.js [hunk 3]
```diff
@@ -131,34 +132,47 @@ const Button = React.createClass({
...
-        marginRight: this.props.children ? 5 : -5
+        marginRight: this.props.children ? 5 : -5,
+        verticalAlign: 'initial'
       },
       spinner: {
-        verticalAlign: 'initial',
         marginRight: -5,
-        padding: !this.props.actionText && this.props.children ? 3 : 0
+        marginTop: -6,
+        padding: !this.props.actionText ? 3 : 0
```
Comment (bsbeeks) [inline src/components/Button.js]: It's minor, but this would read better switched around: `this.props.actionText ? 0 : 3`

File: src/components/Button.js (hunk 1 above)
Comment (jmophoto) [inline src/components/Button.js]: One gotcha on using shorthand styles is that if it is something that you might be overwriting, you can run into issues. Radium throw a warning if you mix long and short hand. To if you use shorthand for the border, and then pass in a prop to change just the width, it complains.

Comment (bsbeeks) [inline src/components/Button.js]: To clarify. I believe the error is only thrown if you mix shorthand/longhand related styles. For example, mixing `border` with `border-width` will throw an error. Mixing `border` with `width` would not throw an error.

Comment (jmophoto) [inline src/components/Button.js]: Yes... I should have said borderWidth. :+1:

Comment (iheartrachie) [inline src/components/Button.js]: Sure enough, I'm getting said error. I'll revert those changes to break them out.

File: src/components/Button.js (hunk 3 above)
Comment (iheartrachie) [inline src/components/Button.js]: Good catch. Cleaner logic! Thanks!

**Comment by bsbeeks** [comment]
:shipit:

File: src/components/Button.js (hunk 1 above)
Comment (scotttball) [inline src/components/Button.js]: @bsbeeks explained it to me offline. mah bad.
