### PR TITLE
Keep the context of RangeSelector on window resize, Fixes #48

### LINKED ISSUE #48: Getting error on RangeSelector component when resizing window
Whenever you resize the window when displaying a RangeSelector component you get the following error: `Uncaught TypeError: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.`

### PR DESCRIPTION
**Pull request by tegon**
The callback of `window.addEventListener` changes the context of the function.
The `_bind` sends the component context to the callback, since there is no option to send the context in `_throttle`. ref https://github.com/lodash/lodash/issues/699

### CODE REVIEW

File: src/components/RangeSelector.js [hunk 1]
```diff
@@ -26,11 +27,11 @@ class RangeSelector extends React.Component {
   componentDidMount () {
     this._setDefaultRangeValues();
 
-    window.addEventListener('resize', _throttle(this._setDefaultRangeValues, 300));
+    window.addEventListener('resize', _throttle(_bind(this._setDefaultRangeValues, this), 300));
```
Comment (bsbeeks) [inline src/components/RangeSelector.js]: Any reason why we can't use the built in `.bind` method?
```javascript
_throttle(this._setDefaultRangeValues.bind(this), 300
```

Comment (tegon) [inline src/components/RangeSelector.js]: I was gonna say that was because of browser support, since `Function.prototype.bind` doesn't exists on IE7 and IE8. 
But then I saw in the `lodash` docs that their support is for IE9 or greater, then at the end it made no difference..
I'll change to use native `.bind` instead.

Comment (bsbeeks) [inline src/components/RangeSelector.js]: Also, for our components we focus on supporting IE10+

Comment (tegon) [inline src/components/RangeSelector.js]: Nice! That's really better. 
Just pushed the change.
